# Project Information
site_name: Yersultan's Documentation
site_url: https://yers-m.github.io/yers_documentation/
site_description: Central Documentation of my projects.
site_author: "Yersultan Mirasbekov"
repo_url: https://github.com/yers-m/yers_documentation
repo_name: documentation
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024

theme:
  name: material
  language: en
  logo: assets/PharMetrX.png
  favicon: assets/PharMetrX.png
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to system preference
  features:
    - search.suggest
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - navigation.footer
    - content.action.edit
    - content.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - announce.dismiss
    - content.action.view
    # - content.tabs.link
    # - header.autohide
    - navigation.expand
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.share
    - toc.follow

# Navigation Structure
nav:
  - Home: index.md
  - Workspace:
    - workspace/index.md
    - workspace/infrastructure_workflow.md
    - workspace/set_up_environment.md
    - workspace/BIDSification.md
    - workspace/comperhensive_tools.md
    - workspace/conversion_tools.md
    - workspace/containers.md
    - workspace/BIDS_datasets.md
    - workspace/BIDS_analysis.md
    - workspace/visualization.md
    - workspace/copying_large_data.md
    - workspace/running_commands_in_background.md
    - workspace/parallelization.md
    - workspace/download_large_data.md
    - workspace/fixing_corrupted_archives.md
  - iAID: 
    - iAID/data.md
    - iAID/BIDSification.md
  - NeuroG Container: 
    - NeuroG Container/motivation.md
    - NeuroG Container/build.md
    - NeuroG Container/how_to_use.md
  - Dicom Extractor:
    - Dicom Extractor/dicom_metadata_extraction_tool.md
    - Dicom Extractor/Usage.md
  - Dicom Reorganizer:
    - Dicom Reorganizer/index.md
    - Dicom Reorganizer/python_package.md
  - Orthanc Server:
    - Orthanc Server/build.md
    - Orthanc Server/usage.md
  # - Blog:
  #     - blog/index.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yers-m/yers_documentation
      name: Documentation

plugins:
  - blog:
      enabled: true
      blog_dir: blog
      authors: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - pymdownx.keys
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.arithmatex:
      generic: true
  - toc:
      toc_depth: 3

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - javascripts/custom.js

extra_css:
  - stylesheets/extra.css

  
# Build Settings
use_directory_urls: true
